/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: b6pDBk4qLGL4uzoLcXsFpxp6h+pKGPex4pIhx7O38KvNFe6YIVN2/6jryG8ZVFVdDAVjjdp25DOeLn5nCpRtQQ==
 */

/* eslint-disable */
// tslint:disable

import SpatialRefSys, {SpatialRefSys_InsertParameters} from './spatial_ref_sys'
import Tech, {Tech_InsertParameters} from './tech'
import UserTech, {UserTech_InsertParameters} from './user_tech'
import Users, {Users_InsertParameters} from './users'

interface DatabaseSchema {
  spatial_ref_sys: {record: SpatialRefSys, insert: SpatialRefSys_InsertParameters};
  tech: {record: Tech, insert: Tech_InsertParameters};
  user_tech: {record: UserTech, insert: UserTech_InsertParameters};
  users: {record: Users, insert: Users_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  SpatialRefSys,
  SpatialRefSys_InsertParameters,
  Tech,
  Tech_InsertParameters,
  UserTech,
  UserTech_InsertParameters,
  Users,
  Users_InsertParameters,
}
