/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: EdlmRBzMBbUExQxXBX3fbdjQc/ABueE4urjFqDXsLeHtInCF6dPYc8TXqdKnnnMC/JidI6H2bROYcKBNojmfjQ==
 */

/* eslint-disable */
// tslint:disable

interface Tech {
  alternative1: (string) | null
  alternative2: (string) | null
  alternative3: (string) | null
  con1: (string) | null
  con2: (string) | null
  con3: (string) | null
  pro1: (string) | null
  pro2: (string) | null
  pro3: (string) | null
  summary: (string) | null
  tech_id: number & {readonly __brand?: 'tech_tech_id'}
  title: string
  udemy_paths: (string) | null
}
export default Tech;

interface Tech_InsertParameters {
  alternative1?: (string) | null
  alternative2?: (string) | null
  alternative3?: (string) | null
  con1?: (string) | null
  con2?: (string) | null
  con3?: (string) | null
  pro1?: (string) | null
  pro2?: (string) | null
  pro3?: (string) | null
  summary?: (string) | null
  tech_id: number & {readonly __brand?: 'tech_tech_id'}
  title: string
  udemy_paths?: (string) | null
}
export type {Tech_InsertParameters}
