/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jHWWDZzGyhKF1ZVOqcC6z07ZE7Wb8E2KA93I9WNk9p6D46wCDH6f63bUU/6ca4hpmUiP8RROYKt7GAarhz4x4g==
 */

/* eslint-disable */
// tslint:disable

interface Users {
  first_name: (string) | null
  last_name: (string) | null
  user_id: number & {readonly __brand?: 'users_user_id'}
  username: (string) | null
}
export default Users;

interface Users_InsertParameters {
  first_name?: (string) | null
  last_name?: (string) | null
  user_id: number & {readonly __brand?: 'users_user_id'}
  username?: (string) | null
}
export type {Users_InsertParameters}
