/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 9Eoann5FYoArSInrUtYujjKlhKbPWsBnMX6rrmsV4UWzTATSFp/ep23ROtH9IRvKyaEDYQ6oPpORguiJ2VStYw==
 */

/* eslint-disable */
// tslint:disable

interface UserTech {
  tech_id: number
  user_id: number
  user_tech_id: number & {readonly __brand?: 'user_tech_user_tech_id'}
}
export default UserTech;

interface UserTech_InsertParameters {
  tech_id: number
  user_id: number
  user_tech_id: number & {readonly __brand?: 'user_tech_user_tech_id'}
}
export type {UserTech_InsertParameters}
